In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv("D:/Projects/result-analysis-aids/data/processed/AI_DS_SEM4_MASTER_RESULTS.csv")

max_marks = {
    "OE": {
        "external": 30,
        "internal": 20,
        "total": 50
    },

    "MINIPROJ": {
        "term_work": 50,
        "oral": 25,
        "total": 75
    },

    "CT": {
        "external": 60,
        "internal": 40,
        "total": 100
    },

    "DBMS": {
        "external": 60,
        "internal": 40,
        "total": 100
    },

    "OS": {
        "external": 60,
        "internal": 40,
        "total": 100
    },

    "DBMS_LAB": {
        "term_work": 25,
        "oral": 25,
        "total": 50
    },

    "OS_LAB": {
        "term_work": 25,
        "oral": 25,
        "total": 50
    },

    "FTS": {
        "external": 60,
        "internal": 40,
        "total": 100
    },

    "TC_LAB": {
        "term_work": 50,
        "oral": 25,
        "total": 75
    },

    "BMD": {
        "term_work": 50,
        "total": 50
    },

    "DT": {
        "term_work": 50,
        "total": 50
    }
}

In [13]:
df.head()

,student_id,seat_no,name,gender,status,ern,college,page,OE_code,OE_name,...,DT_credits,DT_gc,overall_total,maximum_total,percentage,result,remark,aC,aCG,sgpi
0,101410022,101410022,AARADHYA VISHAL SHINDE,MALE,Regular,MU0341120240205831,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,2,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,16.0,549.0,775,70.84,UNSUCCESSFUL,FAILED,22,176.0,0.00000
1,101410023,101410023,ACHARI MOHIT PRABHAKARAN,MALE,Regular,MU0341120240205840,MU-0237: TERNA PUBLIC CHARITABLE TRUSTS TERNA ...,3,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,14.0,553.0,775,71.35,SUCCESSFUL,PASS,23,179.0,7.78261
2,101410024,101410024,ADINATH SOMNATH JAGTAP,MALE,Regular,MU0341120240205802,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,3,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,20.0,616.0,775,79.48,SUCCESSFUL,PASS,23,196.0,8.52174
3,101410025,101410025,ANURAG SANTOSH AMALE,MALE,Regular,MU0341120240205785,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,4,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,18.0,455.0,775,58.71,SUCCESSFUL,PASS,23,137.0,5.95652
4,101410026,101410026,ANVISHA VILAS ALKUTE,FEMALE,Regular,MU0341120240205844,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,4,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,18.0,516.0,775,66.58,SUCCESSFUL,PASS,23,166.0,7.21739

In [14]:
df.tail()

,student_id,seat_no,name,gender,status,ern,college,page,OE_code,OE_name,...,DT_credits,DT_gc,overall_total,maximum_total,percentage,result,remark,aC,aCG,sgpi
83,101410948,101410948,SIDDHESH SANJAY PARDHI,MALE,Regular,MU0341120252010548,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,44,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,14.0,329.0,775,42.45,UNSUCCESSFUL,FAILED,11,70.0,0.00000
84,101410949,101410949,ASHISH DINKAR THOMBARE,MALE,Regular,MU0341120252010542,MU-0237: TERNA PUBLIC CHARITABLE TRUSTS TERNA ...,44,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,14.0,429.0,775,55.35,SUCCESSFUL,PASS,23,126.0,5.47826
85,101410952,101410952,JAYESH VITTHAL BHOR,MALE,Regular,MU0341120252011274,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,45,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,0.0,165.0,775,21.29,UNSUCCESSFUL,FAILED,0,0.0,0.00000
86,101410953,101410953,PRANAY PRAMOD MORE,MALE,Regular,MU0341120252011283,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,45,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,14.0,260.0,775,33.55,UNSUCCESSFUL,FAILED,7,54.0,0.00000
87,101410954,101410954,SHREYA BHIMRAO KHARMATE,FEMALE,Regular,MU0341120252011914,MU-0237: TERNA PUBLIC CHARITABLE TRUSTS TERNA ...,46,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,0.0,164.0,775,21.16,UNSUCCESSFUL,FAILED,0,8.0,0.00000

In [15]:
#I noticed some missing ERN values so I have to find which ones are missing

missing = df.isnull().sum()
print(missing[missing > 0])

#The command says not missing bcz everything is updated properly

Series([], dtype: int64)

In [16]:
print(df.loc[df["ern"].isnull(), "student_id"].to_list())

#I used this and pasted it in antigravity to extract the ern numbers from the pdf via the student_id so it can be automated

#UPDATE: Now it is 0, because it was fixed and updated

# ern                  20 #Initially

# OE_internal           1
# OE_total              1
# CT_external           3
# CT_internal           4
# CT_total              1
# DBMS_LAB_term_work    3
# DBMS_LAB_total        3
# OS_LAB_term_work      2
# OS_LAB_oral           6
# OS_LAB_total          4
# FTS_external          1
# FTS_internal          3
# FTS_total             2
# TC_LAB_term_work      5
# TC_LAB_oral           5
# dtype: int64

#still have to fix all this so yeah next commands:

# output = ""

# for column in missing[missing > 0].index:
#     output += f"\n--- {column} ---\n"
    
#     for student_id in df.loc[df[column].isnull(), "student_id"]:
#         output += f"{student_id} - {column} is missing\n"

# with open("missing_values.txt", "w") as file:
#     file.write(output)

#NOw everything is saved in a txt file which I can directly copy and paste to the AI to

missing = df.isnull().sum()
print(missing[missing > 0])

#yup everything fixed

[]
Series([], dtype: int64)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Columns: 113 entries, student_id to sgpi
dtypes: float64(30), int64(54), object(29)
memory usage: 77.8+ KB

In [18]:
df.shape

(88, 113)

In [19]:
col_list = df.columns.to_list()
print(col_list)

['student_id', 'seat_no', 'name', 'gender', 'status', 'ern', 'college', 'page', 'OE_code', 'OE_name', 'OE_external', 'OE_internal', 'OE_total', 'OE_grade', 'OE_gp', 'OE_credits', 'OE_gc', 'MINIPROJ_code', 'MINIPROJ_name', 'MINIPROJ_term_work', 'MINIPROJ_oral', 'MINIPROJ_total', 'MINIPROJ_grade', 'MINIPROJ_gp', 'MINIPROJ_credits', 'MINIPROJ_gc', 'CT_code', 'CT_name', 'CT_external', 'CT_internal', 'CT_total', 'CT_grade', 'CT_gp', 'CT_credits', 'CT_gc', 'DBMS_code', 'DBMS_name', 'DBMS_external', 'DBMS_internal', 'DBMS_total', 'DBMS_grade', 'DBMS_gp', 'DBMS_credits', 'DBMS_gc', 'OS_code', 'OS_name', 'OS_external', 'OS_internal', 'OS_total', 'OS_grade', 'OS_gp', 'OS_credits', 'OS_gc', 'DBMS_LAB_code', 'DBMS_LAB_name', 'DBMS_LAB_term_work', 'DBMS_LAB_oral', 'DBMS_LAB_total', 'DBMS_LAB_grade', 'DBMS_LAB_gp', 'DBMS_LAB_credits', 'DBMS_LAB_gc', 'OS_LAB_code', 'OS_LAB_name', 'OS_LAB_term_work', 'OS_LAB_oral', 'OS_LAB_total', 'OS_LAB_grade', 'OS_LAB_gp', 'OS_LAB_credits', 'OS_LAB_gc', 'FTS_code', 'FTS_name', 'FTS_external', 'FTS_internal', 'FTS_total', 'FTS_grade', 'FTS_gp', 'FTS_credits', 'FTS_gc', 'TC_LAB_code', 'TC_LAB_name', 'TC_LAB_term_work', 'TC_LAB_oral', 'TC_LAB_total', 'TC_LAB_grade', 'TC_LAB_gp', 'TC_LAB_credits', 'TC_LAB_gc', 'BMD_code', 'BMD_name', 'BMD_term_work', 'BMD_total', 'BMD_grade', 'BMD_gp', 'BMD_credits', 'BMD_gc', 'DT_code', 'DT_name', 'DT_term_work', 'DT_total', 'DT_grade', 'DT_gp', 'DT_credits', 'DT_gc', 'overall_total', 'maximum_total', 'percentage', 'result', 'remark', 'aC', 'aCG', 'sgpi']

In [20]:
df["sgpi"].describe()

count    88.000000
mean      5.041501
std       3.619075
min       0.000000
25%       0.000000
50%       7.130430
75%       7.793480
max       9.130430
Name: sgpi, dtype: float64

In [21]:
print(df["gender"].value_counts())
print(df["sgpi"].value_counts())

gender
MALE      60
FEMALE    28
Name: count, dtype: int64
sgpi
0.00000    29
7.78261     3
7.17391     3
7.43478     3
8.30435     3
7.13043     2
7.65217     2
7.73913     2
8.13043     2
7.39130     2
7.00000     2
6.56522     2
7.34783     2
7.82609     1
8.52174     1
5.95652     1
7.21739     1
8.17391     1
7.91304     1
6.43478     1
8.34783     1
6.39130     1
6.60870     1
7.26087     1
6.78261     1
8.21739     1
8.69565     1
6.26087     1
8.26087     1
6.65217     1
8.73913     1
7.95652     1
9.13043     1
8.08696     1
7.52174     1
8.56522     1
8.39130     1
8.00000     1
8.86957     1
7.30435     1
5.78261     1
5.65217     1
8.65217     1
5.47826     1
Name: count, dtype: int64

In [22]:
#Checking duplicate rows:
print(df.duplicated().sum())

0

In [23]:
print(df[df["student_id"].duplicated(keep=False)])

Empty DataFrame
Columns: [student_id, seat_no, name, gender, status, ern, college, page, OE_code, OE_name, OE_external, OE_internal, OE_total, OE_grade, OE_gp, OE_credits, OE_gc, MINIPROJ_code, MINIPROJ_name, MINIPROJ_term_work, MINIPROJ_oral, MINIPROJ_total, MINIPROJ_grade, MINIPROJ_gp, MINIPROJ_credits, MINIPROJ_gc, CT_code, CT_name, CT_external, CT_internal, CT_total, CT_grade, CT_gp, CT_credits, CT_gc, DBMS_code, DBMS_name, DBMS_external, DBMS_internal, DBMS_total, DBMS_grade, DBMS_gp, DBMS_credits, DBMS_gc, OS_code, OS_name, OS_external, OS_internal, OS_total, OS_grade, OS_gp, OS_credits, OS_gc, DBMS_LAB_code, DBMS_LAB_name, DBMS_LAB_term_work, DBMS_LAB_oral, DBMS_LAB_total, DBMS_LAB_grade, DBMS_LAB_gp, DBMS_LAB_credits, DBMS_LAB_gc, OS_LAB_code, OS_LAB_name, OS_LAB_term_work, OS_LAB_oral, OS_LAB_total, OS_LAB_grade, OS_LAB_gp, OS_LAB_credits, OS_LAB_gc, FTS_code, FTS_name, FTS_external, FTS_internal, FTS_total, FTS_grade, FTS_gp, FTS_credits, FTS_gc, TC_LAB_code, TC_LAB_name, TC_LAB_term_work, TC_LAB_oral, TC_LAB_total, TC_LAB_grade, TC_LAB_gp, TC_LAB_credits, TC_LAB_gc, BMD_code, BMD_name, BMD_term_work, BMD_total, BMD_grade, BMD_gp, BMD_credits, BMD_gc, DT_code, DT_name, DT_term_work, ...]
Index: []

[0 rows x 113 columns]

In [24]:
df.describe()

,student_id,seat_no,page,OE_code,OE_external,OE_internal,OE_total,OE_gp,OE_credits,OE_gc,...,DT_total,DT_gp,DT_credits,DT_gc,overall_total,maximum_total,percentage,aC,aCG,sgpi
count,8.800000e+01,8.800000e+01,88.000000,88.0,88.000000,88.000000,88.000000,88.000000,88.0,88.000000,...,88.000000,88.000000,88.0,88.000000,88.000000,88.0,88.000000,88.000000,88.000000,88.000000
mean,1.014103e+08,1.014103e+08,24.000000,1313311.0,21.534091,14.431818,35.727273,7.500000,2.0,15.000000,...,34.954545,7.477273,2.0,14.954545,479.079545,775.0,61.816364,19.852273,143.011364,5.041501
std,3.798775e+02,3.798775e+02,12.781092,0.0,4.598723,3.728719,7.727734,2.202402,0.0,4.404804,...,11.958654,2.812032,0.0,5.624064,126.699865,0.0,16.348172,6.305516,53.159161,3.619075
min,1.014100e+08,1.014100e+08,2.000000,1313311.0,0.000000,0.000000,0.000000,0.000000,2.0,0.000000,...,0.000000,0.000000,2.0,0.000000,10.000000,775.0,1.290000,0.000000,0.000000,0.000000
25%,1.014100e+08,1.014100e+08,13.000000,1313311.0,18.750000,13.000000,31.000000,7.000000,2.0,14.000000,...,34.000000,7.000000,2.0,14.000000,398.750000,775.0,51.450000,20.000000,111.000000,0.000000
50%,1.014101e+08,1.014101e+08,24.000000,1313311.0,22.000000,15.000000,38.000000,8.000000,2.0,16.000000,...,39.500000,8.500000,2.0,17.000000,517.500000,775.0,66.775000,23.000000,165.000000,7.130430
75%,1.014101e+08,1.014101e+08,35.000000,1313311.0,25.000000,17.000000,41.000000,9.000000,2.0,18.000000,...,42.000000,9.000000,2.0,18.000000,567.000000,775.0,73.160000,23.000000,180.500000,7.793480
max,1.014110e+08,1.014110e+08,46.000000,1313311.0,28.000000,20.000000,47.000000,10.000000,2.0,20.000000,...,45.000000,10.000000,2.0,20.000000,663.000000,775.0,85.550000,23.000000,210.000000,9.130430

In [25]:
df["status"].value_counts()

status
Regular    88
Name: count, dtype: int64

In [26]:
df["result"].value_counts()

result
SUCCESSFUL      59
UNSUCCESSFUL    28
ABSENT           1
Name: count, dtype: int64

In [27]:
print(df.loc[df["sgpi"] > 0, "sgpi"].mean())
print(df["sgpi"].median())
print(df["sgpi"].max())
print(df["sgpi"].min())

7.519527627118643
7.13043
9.13043
0.0

In [28]:
# Pass rate
print((df["sgpi"] > 0).mean() * 100)

# Average SGPI of students who passed
print(df.loc[df["sgpi"] > 0, "sgpi"].mean())

67.04545454545455
7.519527627118643

In [29]:
print(df.mode().to_string())

    student_id    seat_no                            name gender   status                 ern                                      college  page    OE_code                                                OE_name  OE_external  OE_internal  OE_total OE_grade  OE_gp  OE_credits  OE_gc  MINIPROJ_code MINIPROJ_name  MINIPROJ_term_work  MINIPROJ_oral  MINIPROJ_total MINIPROJ_grade  MINIPROJ_gp  MINIPROJ_credits  MINIPROJ_gc    CT_code               CT_name  CT_external  CT_internal  CT_total CT_grade  CT_gp  CT_credits  CT_gc  DBMS_code                   DBMS_name  DBMS_external  DBMS_internal  DBMS_total DBMS_grade  DBMS_gp  DBMS_credits  DBMS_gc    OS_code           OS_name  OS_external  OS_internal  OS_total OS_grade  OS_gp  OS_credits  OS_gc  DBMS_LAB_code                   DBMS_LAB_name  DBMS_LAB_term_work  DBMS_LAB_oral  DBMS_LAB_total DBMS_LAB_grade  DBMS_LAB_gp  DBMS_LAB_credits  DBMS_LAB_gc  OS_LAB_code           OS_LAB_name  OS_LAB_term_work  OS_LAB_oral  OS_LAB_total OS_LAB_grade  OS_LAB_gp  OS_LAB_credits  OS_LAB_gc   FTS_code                                   FTS_name  FTS_external  FTS_internal  FTS_total FTS_grade  FTS_gp  FTS_credits  FTS_gc  TC_LAB_code                          TC_LAB_name  TC_LAB_term_work  TC_LAB_oral  TC_LAB_total TC_LAB_grade  TC_LAB_gp  TC_LAB_credits  TC_LAB_gc   BMD_code                    BMD_name  BMD_term_work  BMD_total BMD_grade  BMD_gp  BMD_credits  BMD_gc    DT_code          DT_name  DT_term_work  DT_total DT_grade  DT_gp  DT_credits  DT_gc  overall_total  maximum_total  percentage      result remark    aC    aCG  sgpi
0    101410022  101410022          AARADHYA VISHAL SHINDE   MALE  Regular  MU0341120240205785  TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI   3.0  1313311.0  Administrative Policy of Chhatrapati Shivaji Maharaja         23.0         15.0      40.0       A+    9.0         2.0   18.0      2014411.0  Mini Project                42.0           20.0            56.0              A          8.0               2.0         16.0  2114111.0  Computational Theory         24.0         29.0      57.0       B+    7.0         3.0   21.0  2114112.0  Database Management System            0.0           23.0        70.0         B+      7.0           3.0     21.0  2114113.0  Operating System         24.0          0.0      58.0        F    0.0         3.0    0.0      2114114.0  Database Management System Lab                20.0           20.0            42.0             A+          9.0               1.0          9.0    2114115.0  Operating System Lab              21.0         21.0          42.0           A+        9.0             1.0        9.0  2304211.0  Fundamentals of Telecommunication Systems          24.0          20.0       49.0        B+     7.0          3.0    21.0    2304212.0  Basic Telecommunication Experiments              18.0         17.0          35.0            A        8.0             1.0        8.0  2994511.0  Business Model Development           43.0       43.0        A+     9.0          2.0    18.0  2994512.0  Design Thinking          42.0      42.0       A+    9.0         2.0   18.0          549.0          775.0       70.84  SUCCESSFUL   PASS  23.0  165.0   0.0
1    101410023  101410023             AAYUSH SANTOSH MORE    NaN      NaN  MU0341120240205786                                          NaN   4.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN      67.0      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN          36.0          27.0       61.0       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN  171.0   NaN
2    101410024  101410024        ACHARI MOHIT PRABHAKARAN    NaN      NaN  MU0341120240205787                                          NaN   5.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN           NaN           NaN       63.0       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN  176.0   NaN
3    101410025  101410025          ADINATH SOMNATH JAGTAP    NaN      NaN  MU0341120240205788                                          NaN   6.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN           NaN           NaN        NaN       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN  179.0   NaN
4    101410026  101410026        AMEYA SURYAKANT GUDHEKAR    NaN      NaN  MU0341120240205789                                          NaN   7.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN           NaN           NaN        NaN       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN  191.0   NaN
5    101410027  101410027            ANURAG SANTOSH AMALE    NaN      NaN  MU0341120240205790                                          NaN   8.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN           NaN           NaN        NaN       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN    NaN   NaN
6    101410028  101410028            ANVISHA VILAS ALKUTE    NaN      NaN  MU0341120240205791                                          NaN   9.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN           NaN           NaN        NaN       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN    NaN   NaN
7    101410029  101410029           ARYAN JAGDISH BHOSALE    NaN      NaN  MU0341120240205792                                          NaN  10.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN           NaN           NaN        NaN       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN    NaN   NaN
8    101410030  101410030           ARYAN PRADEEP TALEKAR    NaN      NaN  MU0341120240205793                                          NaN  11.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN           NaN           NaN        NaN       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN    NaN   NaN
9    101410031  101410031          ASHISH DINKAR THOMBARE    NaN      NaN  MU0341120240205794                                          NaN  12.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN           NaN           NaN        NaN       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN    NaN   NaN
10   101410032  101410032           ATHARVA MAHESH SHELAR    NaN      NaN  MU0341120240205795                                          NaN  13.0        NaN                                                    NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN           NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN        NaN                   NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN        NaN                         NaN            NaN            NaN         NaN        NaN      NaN           NaN      NaN        NaN               NaN          NaN          NaN       NaN      NaN    NaN         NaN    NaN            NaN                             NaN                 NaN            NaN             NaN            NaN          NaN               NaN          NaN          NaN                   NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                                        NaN           NaN           NaN        NaN       NaN     NaN          NaN     NaN          NaN                                  NaN               NaN          NaN           NaN          NaN        NaN             NaN        NaN        NaN                         NaN            NaN        NaN       NaN     NaN          NaN     NaN        NaN              NaN           NaN       NaN      NaN    NaN         NaN    NaN            NaN            NaN         NaN         NaN    NaN   NaN    NaN   NaN

In [30]:
print(df["sgpi"].mode())

0    0.0
Name: sgpi, dtype: float64

In [31]:
passing_sgpi = df.loc[df["sgpi"] > 0, "sgpi"]
print(passing_sgpi.min())
print(passing_sgpi.max())
print(passing_sgpi.max() - passing_sgpi.min())

5.47826
9.13043
3.652170000000001

In [32]:
print(passing_sgpi.std())

0.8316873383656388

In [33]:
print(passing_sgpi.var())
df["college"].value_counts()

0.6917038287977206

college
TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI                                            68
MU-0237: TERNA PUBLIC CHARITABLE TRUSTS TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI    20
Name: count, dtype: int64

In [34]:
df["college"] = df["college"].replace("TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI", "MU-0237: TERNA PUBLIC CHARITABLE TRUSTS TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI ")

In [35]:
#Rows
df.shape[0]

88

In [36]:
#columns
df.shape[1]

113

In [37]:
#display column names
df.columns

Index(['student_id', 'seat_no', 'name', 'gender', 'status', 'ern', 'college',
       'page', 'OE_code', 'OE_name',
       ...
       'DT_credits', 'DT_gc', 'overall_total', 'maximum_total', 'percentage',
       'result', 'remark', 'aC', 'aCG', 'sgpi'],
      dtype='object', length=113)

In [38]:
df["name"]

0       AARADHYA VISHAL SHINDE
1     ACHARI MOHIT PRABHAKARAN
2       ADINATH SOMNATH JAGTAP
3         ANURAG SANTOSH AMALE
4         ANVISHA VILAS ALKUTE
                ...
83      SIDDHESH SANJAY PARDHI
84      ASHISH DINKAR THOMBARE
85         JAYESH VITTHAL BHOR
86          PRANAY PRAMOD MORE
87     SHREYA BHIMRAO KHARMATE
Name: name, Length: 88, dtype: object

In [39]:
df[["name", "percentage", "sgpi"]]

                        name  percentage     sgpi
0     AARADHYA VISHAL SHINDE       70.84  0.00000
1   ACHARI MOHIT PRABHAKARAN       71.35  7.78261
2     ADINATH SOMNATH JAGTAP       79.48  8.52174
3       ANURAG SANTOSH AMALE       58.71  5.95652
4       ANVISHA VILAS ALKUTE       66.58  7.21739
..                       ...         ...      ...
83    SIDDHESH SANJAY PARDHI       42.45  0.00000
84    ASHISH DINKAR THOMBARE       55.35  5.47826
85       JAYESH VITTHAL BHOR       21.29  0.00000
86        PRANAY PRAMOD MORE       33.55  0.00000
87   SHREYA BHIMRAO KHARMATE       21.16  0.00000

[88 rows x 3 columns]

In [40]:
print(df.loc[df["sgpi"] > 8, "name"])

2       ADINATH SOMNATH JAGTAP
18        DURUGKAR ASMITA AMIT
24       KAMBLE SARTHAK PRAVIN
25       KRUSHNA VILAS BORHADE
27          MAHANGADE OM VIJAY
35          PIYUSH HARESH KOLI
37        PRAJWAL ASHOK ZOLAGE
39     PRASAD KISAN BHAJNAWALE
45      SAHIL SUBHASH KAVANKAR
47     SALUNKHE DARSHAN DEEPAK
48    SAMIKSHA RAJENDRA BODAKE
52       SHIVAM VILAS BANDEKAR
53      SHRAVANI HANSRAJ PATIL
56      SHRUNJAL PRADEEP PATIL
62       TEJAS JITENDRA SAWANT
64        UNNATI DINESH CHAVAN
71       SHRAVANI VISHWAS MANE
76    MANGILAL SHRAVAN MALVIYA
Name: name, dtype: object

In [41]:
print(df.loc[df["sgpi"] > 8, ["name", "sgpi"]])

                        name     sgpi
2     ADINATH SOMNATH JAGTAP  8.52174
18      DURUGKAR ASMITA AMIT  8.13043
24     KAMBLE SARTHAK PRAVIN  8.17391
25     KRUSHNA VILAS BORHADE  8.30435
27        MAHANGADE OM VIJAY  8.34783
35        PIYUSH HARESH KOLI  8.30435
37      PRAJWAL ASHOK ZOLAGE  8.21739
39   PRASAD KISAN BHAJNAWALE  8.69565
45    SAHIL SUBHASH KAVANKAR  8.26087
47   SALUNKHE DARSHAN DEEPAK  8.13043
48  SAMIKSHA RAJENDRA BODAKE  8.73913
52     SHIVAM VILAS BANDEKAR  9.13043
53    SHRAVANI HANSRAJ PATIL  8.30435
56    SHRUNJAL PRADEEP PATIL  8.08696
62     TEJAS JITENDRA SAWANT  8.56522
64      UNNATI DINESH CHAVAN  8.39130
71     SHRAVANI VISHWAS MANE  8.86957
76  MANGILAL SHRAVAN MALVIYA  8.65217

In [42]:
(df["sgpi"] > 8).sum()

np.int64(18)

In [43]:
print(df.loc[df["sgpi"].idxmax(), ["name", "sgpi", "percentage"]])

name          SHIVAM VILAS BANDEKAR
sgpi                        9.13043
percentage                    85.55
Name: 52, dtype: object

In [44]:
passing = df[df["sgpi"] > 0]

print(passing.loc[passing["sgpi"].idxmin(), ["name", "sgpi", "percentage"]])

name          ASHISH DINKAR THOMBARE
sgpi                         5.47826
percentage                     55.35
Name: 84, dtype: object

In [45]:
print((df.loc[df["sgpi"] == 0, "name"]).count())

29

In [46]:
print(df.loc[df["percentage"] > 75, "name"])

2          ADINATH SOMNATH JAGTAP
8               BHOJANE SAISURESH
24          KAMBLE SARTHAK PRAVIN
25          KRUSHNA VILAS BORHADE
27             MAHANGADE OM VIJAY
35             PIYUSH HARESH KOLI
37           PRAJWAL ASHOK ZOLAGE
39        PRASAD KISAN BHAJNAWALE
47        SALUNKHE DARSHAN DEEPAK
48       SAMIKSHA RAJENDRA BODAKE
52          SHIVAM VILAS BANDEKAR
53         SHRAVANI HANSRAJ PATIL
56         SHRUNJAL PRADEEP PATIL
62          TEJAS JITENDRA SAWANT
64           UNNATI DINESH CHAVAN
68    JETITHOR SRUSHTI VIJAYKUMAR
70          NIKITA SANTOSH MADANE
71          SHRAVANI VISHWAS MANE
76       MANGILAL SHRAVAN MALVIYA
Name: name, dtype: object

In [47]:
print(df.loc[(df["percentage"] >= 60) & (df["percentage"] >= 70), ["name", "percentage", "sgpi"]])

                           name  percentage     sgpi
0        AARADHYA VISHAL SHINDE       70.84  0.00000
1      ACHARI MOHIT PRABHAKARAN       71.35  7.78261
2        ADINATH SOMNATH JAGTAP       79.48  8.52174
8             BHOJANE SAISURESH       76.13  7.82609
9          BOHRA RITHVIK SATISH       70.84  7.73913
11  CHAUDHARI KRUSHNA PANDURANG       71.10  7.78261
12          CHAVAN RUDRA MILIND       72.00  7.65217
18         DURUGKAR ASMITA AMIT       74.58  8.13043
19          GAIKWAD SOHAM YADAV       70.84  7.43478
24        KAMBLE SARTHAK PRAVIN       75.48  8.17391
25        KRUSHNA VILAS BORHADE       75.10  8.30435
26       LODHI BHUPESH MAHENDRA       72.90  7.91304
27           MAHANGADE OM VIJAY       78.32  8.34783
35           PIYUSH HARESH KOLI       77.42  8.30435
37         PRAJWAL ASHOK ZOLAGE       77.68  8.21739
39      PRASAD KISAN BHAJNAWALE       78.71  8.69565
45       SAHIL SUBHASH KAVANKAR       74.06  8.26087
47      SALUNKHE DARSHAN DEEPAK       75.61  8.13043
48     SAMIKSHA RAJENDRA BODAKE       80.90  8.73913
49        SARTHAK SUNIL HUNDARE       73.55  7.95652
52        SHIVAM VILAS BANDEKAR       85.55  9.13043
53       SHRAVANI HANSRAJ PATIL       76.65  8.30435
54      SHREYA MAHADEO NALAVADE       73.03  7.78261
55            SHRIYA NILESH DEO       71.87  7.65217
56       SHRUNJAL PRADEEP PATIL       76.39  8.08696
62        TEJAS JITENDRA SAWANT       79.10  8.56522
64         UNNATI DINESH CHAVAN       78.19  8.39130
68  JETITHOR SRUSHTI VIJAYKUMAR       75.48  8.00000
70        NIKITA SANTOSH MADANE       76.39  0.00000
71        SHRAVANI VISHWAS MANE       83.74  8.86957
76     MANGILAL SHRAVAN MALVIYA       79.23  8.65217
78         PREETI SANJEEV SINGH       70.84  7.73913

In [48]:
print(df.sort_values("sgpi", ascending=False)[["name", "sgpi"]].head(5))

                        name     sgpi
52     SHIVAM VILAS BANDEKAR  9.13043
71     SHRAVANI VISHWAS MANE  8.86957
48  SAMIKSHA RAJENDRA BODAKE  8.73913
39   PRASAD KISAN BHAJNAWALE  8.69565
76  MANGILAL SHRAVAN MALVIYA  8.65217

In [49]:
passing = df[df["sgpi"] > 0]

print(passing.sort_values("sgpi", ascending=True)[["name", "sgpi"]].head(5))

                      name     sgpi
84  ASHISH DINKAR THOMBARE  5.47826
75   ARYAN PRADEEP TALEKAR  5.65217
74          MORE RAJ VINOD  5.78261
3     ANURAG SANTOSH AMALE  5.95652
44      RAWAL HARSH CHETAN  6.26087

In [50]:
df["result"].value_counts()

result
SUCCESSFUL      59
UNSUCCESSFUL    28
ABSENT           1
Name: count, dtype: int64

In [51]:
print(df.loc[df["sgpi"] > 0, "percentage"].mean())

70.43322033898306

In [52]:
max_marks = df["DBMS_total"].max()
print(df[df["DBMS_total"] == max_marks])

    student_id    seat_no                   name gender   status  \
52   101410074  101410074  SHIVAM VILAS BANDEKAR   MALE  Regular

                   ern                                            college  \
52  MU0341120252007818  MU-0237: TERNA PUBLIC CHARITABLE TRUSTS TERNA ...

    page  OE_code                                            OE_name  ...  \
52    28  1313311  Administrative Policy of Chhatrapati Shivaji M...  ...

    DT_credits  DT_gc  overall_total maximum_total  percentage      result  \
52           2   18.0          663.0           775       85.55  SUCCESSFUL

    remark  aC    aCG     sgpi
52    PASS  23  210.0  9.13043

[1 rows x 113 columns]

In [53]:
min_marks = df["DBMS_total"].min()
print(df[df["DBMS_total"] == min_marks])

    student_id    seat_no                      name gender   status  \
67   101410926  101410926  RAYHAAN LIYAKAT KALSEKAR   MALE  Regular

                   ern                                            college  \
67  MU0341120240205806  MU-0237: TERNA PUBLIC CHARITABLE TRUSTS TERNA ...

    page  OE_code                                            OE_name  ...  \
67    36  1313311  Administrative Policy of Chhatrapati Shivaji M...  ...

    DT_credits  DT_gc  overall_total maximum_total  percentage  result  \
67           2    0.0           10.0           775        1.29  ABSENT

    remark  aC  aCG  sgpi
67  ABSENT  21  0.0   0.0

[1 rows x 113 columns]

In [64]:
without_abs = df.loc[df["result"] != "ABSENT"]

In [72]:
min_marks = without_abs["DBMS_total"].min()

print(without_abs.loc[without_abs["DBMS_total"] == min_marks, "DBMS_total"])

17    1
Name: DBMS_total, dtype: int64